apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  labels:
    name: crossplane-provider-provider-helm-system-dev
  name: crossplane:provider:provider-helm:system:dev
rules:
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - watch
      - patch
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - watch
      - patch
      - update
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - watch
      - patch
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: {}
  labels:
    name: crossplane-provider-provider-helm-system-dev
  name: crossplane:provider:provider-helm:system:dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane:provider:provider-helm:system:dev
subjects:
  - kind: ServiceAccount
    name: provider-helm
    namespace: syn-crossplane
