apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  labels:
    name: xvshnredis.vshn.appcat.vshn.io
  name: xvshnredis.vshn.appcat.vshn.io
spec:
  claimNames:
    kind: VSHNRedis
    plural: vshnredis
  connectionSecretKeys:
    - ca.crt
    - tls.crt
    - tls.key
    - REDIS_HOST
    - REDIS_PORT
    - REDIS_USERNAME
    - REDIS_PASSWORD
    - REDIS_URL
  defaultCompositionRef:
    name: vshnredis.vshn.appcat.vshn.io
  group: vshn.appcat.vshn.io
  names:
    kind: XVSHNRedis
    plural: xvshnredis
  versions:
    - name: v1
      referenceable: true
      schema:
        openAPIV3Schema:
          description: VSHNRedis is the API for creating Redis clusters.
          properties:
            spec:
              description: Spec defines the desired state of a VSHNRedis.
              properties:
                parameters:
                  default: {}
                  description: Parameters are the configurable fields of a VSHNRedis.
                  properties:
                    service:
                      default: {}
                      description: Service contains Redis DBaaS specific properties
                      properties:
                        redisSettings:
                          description: RedisSettings contains additional Redis settings.
                          type: string
                        version:
                          default: '7.0'
                          description: Version contains supported version of Redis.
                            Multiple versions are supported. The latest version "7.0"
                            is the default version.
                          enum:
                            - '6.2'
                            - '7.0'
                          type: string
                      type: object
                    size:
                      default: {}
                      description: Size contains settings to control the sizing of
                        a service.
                      properties:
                        cpuLimits:
                          default: 500m
                          description: CPULimits defines the limits amount of Kubernetes
                            CPUs for an instance.
                          type: string
                        cpuRequests:
                          default: 500m
                          description: CPURequests defines the requests amount of
                            Kubernetes CPUs for an instance.
                          type: string
                        disk:
                          default: 5Gi
                          description: Disk defines the amount of disk space for an
                            instance.
                          type: string
                        memoryLimits:
                          default: 2048Mi
                          description: MemoryLimits defines the limits amount of memory
                            in units of bytes for an instance.
                          type: string
                        memoryRequests:
                          default: 2048Mi
                          description: MemoryRequests defines the requests amount
                            of memory in units of bytes for an instance.
                          type: string
                      type: object
                    tls:
                      default: {}
                      description: TLS contains settings to control tls traffic of
                        a service.
                      properties:
                        authClients:
                          default: true
                          description: TLSAuthClients enables client authentication
                            requirement
                          type: boolean
                        enabled:
                          default: true
                          description: TLSEnabled enables TLS traffic for the service
                          type: boolean
                      type: object
                  type: object
              type: object
            status:
              description: Status reflects the observed state of a VSHNRedis.
              properties:
                effectiveVersion:
                  type: string
                caCertificateDebug:
                  items:
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition
                          transitioned from one status to another.
                        format: date-time
                        type: string
                      message:
                        description: Message is a human-readable message indicating
                          details about the transition.
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        description: ObservedGeneration represents the .metadata.generation
                          that the condition was set based upon. For instance, if
                          .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration
                          is 9, the condition is out of date with respect to the current
                          state of the instance.
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        description: Reason contains a programmatic identifier indicating
                          the reason for the condition's last transition.
                        maxLength: 1024
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        description: Status of the condition, one of True, False,
                          Unknown.
                        enum:
                          - 'True'
                          - 'False'
                          - Unknown
                        type: string
                      type:
                        description: Type of condition.
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    type: object
                  type: array
                clientCertificateDebug:
                  items:
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition
                          transitioned from one status to another.
                        format: date-time
                        type: string
                      message:
                        description: Message is a human-readable message indicating
                          details about the transition.
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        description: ObservedGeneration represents the .metadata.generation
                          that the condition was set based upon. For instance, if
                          .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration
                          is 9, the condition is out of date with respect to the current
                          state of the instance.
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        description: Reason contains a programmatic identifier indicating
                          the reason for the condition's last transition.
                        maxLength: 1024
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        description: Status of the condition, one of True, False,
                          Unknown.
                        enum:
                          - 'True'
                          - 'False'
                          - Unknown
                        type: string
                      type:
                        description: Type of condition.
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    type: object
                  type: array
                localCADebug:
                  items:
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition
                          transitioned from one status to another.
                        format: date-time
                        type: string
                      message:
                        description: Message is a human-readable message indicating
                          details about the transition.
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        description: ObservedGeneration represents the .metadata.generation
                          that the condition was set based upon. For instance, if
                          .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration
                          is 9, the condition is out of date with respect to the current
                          state of the instance.
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        description: Reason contains a programmatic identifier indicating
                          the reason for the condition's last transition.
                        maxLength: 1024
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        description: Status of the condition, one of True, False,
                          Unknown.
                        enum:
                          - 'True'
                          - 'False'
                          - Unknown
                        type: string
                      type:
                        description: Type of condition.
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    type: object
                  type: array
                namespaceDebug:
                  description: RedisConditions contains the status conditions of the
                    backing object.
                  items:
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition
                          transitioned from one status to another.
                        format: date-time
                        type: string
                      message:
                        description: Message is a human-readable message indicating
                          details about the transition.
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        description: ObservedGeneration represents the .metadata.generation
                          that the condition was set based upon. For instance, if
                          .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration
                          is 9, the condition is out of date with respect to the current
                          state of the instance.
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        description: Reason contains a programmatic identifier indicating
                          the reason for the condition's last transition.
                        maxLength: 1024
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        description: Status of the condition, one of True, False,
                          Unknown.
                        enum:
                          - 'True'
                          - 'False'
                          - Unknown
                        type: string
                      type:
                        description: Type of condition.
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    type: object
                  type: array
                selfSignedIssuerDebug:
                  items:
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition
                          transitioned from one status to another.
                        format: date-time
                        type: string
                      message:
                        description: Message is a human-readable message indicating
                          details about the transition.
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        description: ObservedGeneration represents the .metadata.generation
                          that the condition was set based upon. For instance, if
                          .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration
                          is 9, the condition is out of date with respect to the current
                          state of the instance.
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        description: Reason contains a programmatic identifier indicating
                          the reason for the condition's last transition.
                        maxLength: 1024
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        description: Status of the condition, one of True, False,
                          Unknown.
                        enum:
                          - 'True'
                          - 'False'
                          - Unknown
                        type: string
                      type:
                        description: Type of condition.
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    type: object
                  type: array
                serverCertificateDebug:
                  items:
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition
                          transitioned from one status to another.
                        format: date-time
                        type: string
                      message:
                        description: Message is a human-readable message indicating
                          details about the transition.
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        description: ObservedGeneration represents the .metadata.generation
                          that the condition was set based upon. For instance, if
                          .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration
                          is 9, the condition is out of date with respect to the current
                          state of the instance.
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        description: Reason contains a programmatic identifier indicating
                          the reason for the condition's last transition.
                        maxLength: 1024
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        description: Status of the condition, one of True, False,
                          Unknown.
                        enum:
                          - 'True'
                          - 'False'
                          - Unknown
                        type: string
                      type:
                        description: Type of condition.
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    type: object
                  type: array
              type: object
          required:
            - spec
          type: object
      served: true
